In [1]:
import numpy as np

In [4]:
a = [10,20,30]
b = [70,80,100]

In [6]:
np.sum([a,b])   #always take values as list

310

In [7]:
np.sum([a,b], axis=0)     #row-wise, output=new row

array([ 80, 100, 130])

In [8]:
np.sum([a,b], axis=1)     #column-wise, output=new column

array([ 60, 250])

In [9]:
np.subtract(b,a)

array([60, 60, 70])

In [10]:
np.subtract(a,b)

array([-60, -60, -70])

In [13]:
np.multiply(a,b)

array([ 700, 1600, 3000])

In [14]:
np.divide(a,b)

array([0.14285714, 0.25      , 0.3       ])

In [15]:
a=np.array([1,2,3,4,5])
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [17]:
x=np.array([[0,1],[2,3],[4,5]])
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [18]:
y=np.array([121,576,729,196,784])
y

array([121, 576, 729, 196, 784])

In [19]:
np.sqrt(y)

array([11., 24., 27., 14., 28.])

In [20]:
np.sqrt(0)

0.0

In [21]:
np.sqrt(-36)

C:\Users\Joyita\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


nan

In [22]:
np.sqrt(71)

8.426149773176359

In [23]:
#Sin Function  - sin(30deg = 1\2)
np.sin(30)

-0.9880316240928618

In [25]:
# sin/cosin accept angles as radian  - (180degree = pi radian)
np.sin(30*3.14/180)

0.4997701026431024

In [27]:
np.cos(60*3.14/180)

0.5004596890082058

In [28]:
lst=[1,2,'abc']             #lists are heterogeneous and array are homogeneous
lst

[1, 2, 'abc']

In [30]:
type(lst)

list

In [31]:
type(lst[0])

int

In [32]:
type(lst[2])

str

In [33]:
np.array([1,2,'ab'])

array(['1', '2', 'ab'], dtype='<U11')

In [34]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [36]:
#even nos till 20
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
#Aggregate Functions

In [37]:
a = np.array([1,2,3,7,8,9,10,11])
a

array([ 1,  2,  3,  7,  8,  9, 10, 11])

In [38]:
print("sum: " + np.sum(a))

TypeError: can only concatenate str (not "numpy.int32") to str

In [42]:
print("sum: " + str(np.sum(a)))
print("minimum: " + str(np.min(a)))
print("maximum: " + str(np.max(a)))
print("mean: " + str(np.mean(a)))
print("median: " + str(np.median(a)))
print("corelation cofficient: " + str(np.corrcoef(a)))
print("standard deviation: " + str(np.std(a)))

sum: 51
minimum: 1
maximum: 11
mean: 6.375
median: 7.5
corelation cofficient: 1.0
standard deviation: 3.6033838263498934


In [ ]:
#Array comparison element-wise

In [43]:
a = [1,2,4]
b = [2,2,4]
c = [1,2,4]

In [44]:
np.equal(a,b)

array([False,  True,  True])

In [45]:
np.equal(a,c)

array([ True,  True,  True])

In [46]:
#Array-wise comparison

In [47]:
np.array_equal(a,c)

True

In [48]:
np.array_equal(a,b)

False

In [49]:
#Array concatenation
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x)
print(y)

[1 2 3]
[4 5 6]


In [50]:
np.concatenate((x,y))                       #always take values as tuple

array([1, 2, 3, 4, 5, 6])

In [52]:
#stack row-wise
np.hstack((x,y))

array([1, 2, 3, 4, 5, 6])

In [53]:
#stack column-wise
np.vstack((x,y))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#numpy is faster than list
import time

def using_list():
    t1=time.time()
    x=range(100000)
    y=range(100000)
    z=[x[i] + y[i] for i in range(len(x))]
    print(z[0:5])
    return time.time() - t1

def using_numpy():
    t2=time.time()
    a=np.arange(100000)
    b=np.arange(100000)
    c= a + b
    return time.time -t2

list_time = using_list()
numpy_time = using_numpy()
