In [1]:
import numpy as np
import pandas as pd

In [2]:
# Array Initialization
A = np.array([[1,2],[2,4]])
B = np.array([[3,4],[4,5]])

In [3]:
A

array([[1, 2],
       [2, 4]])

In [4]:
B

array([[3, 4],
       [4, 5]])

In [5]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
C = np.array([[[1,2],[3,4]],[[4,5],[7,8]]])
C

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [7, 8]]])

In [8]:
A

array([[1, 2],
       [2, 4]])

In [9]:
# Array Inspection
np.size(A)          # no of elements

4

In [10]:
np.shape(A)     # no of rows, columns

(2, 2)

In [11]:
len(A)          # no of rows

2

In [12]:
len(A[0])       # no of columns

2

In [13]:
C

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [7, 8]]])

In [14]:
len(C)

2

In [15]:
len(C[0])

2

In [16]:
np.size(C)

8

In [17]:
np.shape(C)

(2, 2, 2)

In [18]:
A.ndim

2

In [19]:
C.ndim

3

# **Matrix Operations**

**Addition**

In [32]:
# Addition
print(A)
print(B)

[[1 2]
 [2 4]]
[[3 4]
 [4 5]]


In [21]:
result = np.array([[0,0],[0,0]])
for i in range(len(A)):
    for j in range(len(A[0])):
        result[i][j] = A[i][j] + B[i][j]

In [22]:
for r in result:
    print(r)

[4 6]
[6 9]


In [23]:
result

array([[4, 6],
       [6, 9]])

In [24]:
#using inbuilt func
np.add(A,B)

array([[4, 6],
       [6, 9]])

**Subtraction**

In [25]:
# Subtraction
D=np.array([[5,2,2],[4,6,7]])
E=np.array([[4,5,4],[2,3,2],[1,2,4]])

In [26]:
D

array([[5, 2, 2],
       [4, 6, 7]])

In [27]:
D.shape

(2, 3)

In [28]:
E

array([[4, 5, 4],
       [2, 3, 2],
       [1, 2, 4]])

In [29]:
E.shape

(3, 3)

In [34]:
sub_result = np.array([[0,0,0],[0,0,0],[0,0,0]])
for i in range(len(D)):
    for j in range(len(D[0])):
        sub_result[i][j] = D[i][j] - E[i][j]
        
print(sub_result)

[[ 1 -3 -2]
 [ 2  3  5]
 [ 0  0  0]]


In [35]:
for r in sub_result:
    print(r)

[ 1 -3 -2]
[2 3 5]
[0 0 0]


In [41]:
s_result = np.array([[0,0,0],[0,0,0],[0,0,0]])
for i in range(len(D)):
    for j in range(len(E[0])):
        s_result[i][j] = D[i][j] - E[i][j]
        
print(s_result)

[[ 1 -3 -2]
 [ 2  3  5]
 [ 0  0  0]]


In [42]:
len(D)

2

In [43]:
len(D[0])

3

In [44]:
len(E)

3

In [45]:
len(E[0])

3

In [46]:
# using inbuilt function
np.subtract(D,E)                 # only applicable only if both matrix has same size

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

**Multiplication**

In [47]:
# Scalar Multiplication
s = np.array([[5,2,9],[4,6,7],[1,3,8]])
scalar = 2

In [48]:
s

array([[5, 2, 9],
       [4, 6, 7],
       [1, 3, 8]])

In [50]:
mul_result = np.array([[0,0,0],[0,0,0],[0,0,0]])
for i in range(len(s)):
    for j in range(len(s[0])):
        mul_result[i][j] = s[i][j]*scalar
        
print(mul_result)

[[10  4 18]
 [ 8 12 14]
 [ 2  6 16]]


In [51]:
# DOT PRODUCT with first matrix of 3X3 and second matrix of 3X1
S=np.array([[5,2,9],[4,6,7],[1,3,8]])
T=np.array([[1],[2],[3]])
print(S)
print(T)

[[5 2 9]
 [4 6 7]
 [1 3 8]]
[[1]
 [2]
 [3]]


In [52]:
result = np.dot(S,T)
result

array([[36],
       [37],
       [31]])

In [53]:
# DOT PRODUCT with first matrix of 3X3 and second matrix of 3X2
S1=np.array([[5,2,9],[4,6,7],[1,3,8]])
T1=np.array([[1,2],[2,1],[3,2]])
print(S1)
print(T1)

[[5 2 9]
 [4 6 7]
 [1 3 8]]
[[1 2]
 [2 1]
 [3 2]]


In [54]:
result1 = np.dot(S1,T1)
result1

array([[36, 30],
       [37, 28],
       [31, 21]])

In [55]:
# DOT PRODUCT with first matrix of 3X3 and second matrix of 3X3
S2=np.array([[5,2,9],[4,6,7],[1,3,8]])
T2=np.array([[1,2,1],[3,1,2],[4,2,1]])
print(S2)
print(T2)

[[5 2 9]
 [4 6 7]
 [1 3 8]]
[[1 2 1]
 [3 1 2]
 [4 2 1]]


In [56]:
result2 = np.dot(S2,T2)
result2

array([[47, 30, 18],
       [50, 28, 23],
       [42, 21, 15]])

In [57]:
# CROSS Product
a=np.array([[3],[2],[8]])
b=np.array([[2],[9],[7]])
print(a)
print(b)

[[3]
 [2]
 [8]]
[[2]
 [9]
 [7]]


In [58]:
rslt = np.cross(a,b)
rslt                       # no of columns of a = no of rows of b

ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [59]:
a=np.array([[3],[2],[8]]).reshape(-1)
b=np.array([[2],[9],[7]]).reshape(-1)
print(a)
print(b)

[3 2 8]
[2 9 7]


In [60]:
np.cross(a,b)

array([-58,  -5,  23])

In [64]:
S.shape

(3, 3)

In [70]:
T.shape

(3, 1)

In [71]:
np.cross(S,T)

ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [72]:
# Additional approach
cross_result=np.cross(np.transpose(a),np.transpose(b))

In [73]:
np.transpose(a)

array([3, 2, 8])

In [74]:
np.transpose(b)

array([2, 9, 7])

In [75]:
cross_result

array([-58,  -5,  23])

**TRANSPOSE of matrix**

In [76]:
R=np.array([[1,1,0],[2,1,2]])
R_transpose = np.transpose(R)
R_transpose

array([[1, 2],
       [1, 1],
       [0, 2]])

**INVERSE of matrix**

In [77]:
I=np.array([[2,1],[4,3]])
I_inv = np.linalg.inv(I)
I_inv

array([[ 1.5, -0.5],
       [-2. ,  1. ]])

In [78]:
F=np.array([[1,1,2],[2,1,2],[2,3,1]])
np.linalg.inv(F)

array([[-1. ,  1. ,  0. ],
       [ 0.4, -0.6,  0.4],
       [ 0.8, -0.2, -0.2]])

# **MATRIX DECOMPOSITION**

**1. LU DECOMPOSITION**

In [79]:
from scipy.linalg import lu

In [80]:
J=np.array([[1,2,3],[3,4,1],[1,3,2]])
P,L,U = lu(J)
print("P : ",P)
print("L : ",L)
print("U : ",U)
result = P.dot(L).dot(U)
print(result)

P :  [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
L :  [[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.33333333 0.4        1.        ]]
U :  [[3.         4.         1.        ]
 [0.         1.66666667 1.66666667]
 [0.         0.         2.        ]]
[[1. 2. 3.]
 [3. 4. 1.]
 [1. 3. 2.]]


**2. QR Decomposition**

In [81]:
from numpy.linalg import qr

In [83]:
K=np.array([[1,2],[4,1],[5,1]])
Q,R = qr(K)
print(Q)
print(R)
qr_result = Q.dot(R)
print(qr_result)

[[-0.15430335  0.98415288]
 [-0.6172134  -0.02696309]
 [-0.77151675 -0.1752601 ]]
[[-6.4807407  -1.69733685]
 [ 0.          1.76608256]]
[[1. 2.]
 [4. 1.]
 [5. 1.]]


**3. CHOLESKY Decomposition**

In [84]:
from numpy.linalg import cholesky

In [85]:
M = np.array([[2,1],[1,2]])
L = cholesky(M)
T = np.transpose(L)
print(M)
print(L)
print(T)
cholesky_result = L.dot(T)
print(cholesky_result)

[[2 1]
 [1 2]]
[[1.41421356 0.        ]
 [0.70710678 1.22474487]]
[[1.41421356 0.70710678]
 [0.         1.22474487]]
[[2. 1.]
 [1. 2.]]
